<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{

    public function run()
    {
        DB::table('countries')->delete();

        $countries = array(
            array('id' => '1','code' => 'AF','name' => 'Afghanistan','numcode' => '4','phonecode' => '93'),
            array('id' => '2','code' => 'AL','name' =>  'Albania','numcode' => '8','phonecode' => '355'),
            array('id' => '3','code' => 'DZ','name' =>  'Algeria','numcode' => '12','phonecode' => '213'),
            array('id' => '4','code' => 'AS','name' => 'American Samoa','numcode' => '16','phonecode' => '1684'),
            array('id' => '5','code' => 'AD','name' => 'Andorra','numcode' => '20','phonecode' => '376'),
            array('id' => '6','code' => 'AO','name' =>  'Angola','numcode' => '24','phonecode' => '244'),
            array('id' => '7','code' => 'AI','name' =>  'Anguilla','numcode' => '660','phonecode' => '1264'),
            array('id' => '8','code' => 'AQ','name' =>  'Antarctica','numcode' => NULL,'phonecode' => '0'),
            array('id' => '9','code' => 'AG','name' =>  'Antigua and Barbuda','numcode' => '28','phonecode' => '1268'),
            array('id' => '10','code' => 'AR','name' =>  'Argentina','numcode' => '32','phonecode' => '54'),
            array('id' => '11','code' => 'AM','name' =>  'Armenia','numcode' => '51','phonecode' => '374'),
            array('id' => '12','code' => 'AW','name' =>  'Aruba','numcode' => '533','phonecode' => '297'),
            array('id' => '13','code' => 'AU','name' =>  'Australia','numcode' => '36','phonecode' => '61'),
            array('id' => '14','code' => 'AT','name' =>  'Austria','numcode' => '40','phonecode' => '43'),
            array('id' => '15','code' => 'AZ','name' => 'Azerbaijan','numcode' => '31','phonecode' => '994'),
            array('id' => '16','code' => 'BS','name' => 'Bahamas','numcode' => '44','phonecode' => '1242'),
            array('id' => '17','code' => 'BH','name' =>  'Bahrain','numcode' => '48','phonecode' => '973'),
            array('id' => '18','code' => 'BD','name' =>  'Bangladesh','numcode' => '50','phonecode' => '880'),
            array('id' => '19','code' => 'BB','name' =>  'Barbados','numcode' => '52','phonecode' => '1246'),
            array('id' => '20','code' => 'BY','name' =>  'Belarus','numcode' => '112','phonecode' => '375'),
            array('id' => '21','code' => 'BE','name' =>  'Belgium','numcode' => '56','phonecode' => '32'),
            array('id' => '22','code' => 'BZ','name' =>  'Belize','numcode' => '84','phonecode' => '501'),
            array('id' => '23','code' => 'BJ','name' =>  'Benin','numcode' => '204','phonecode' => '229'),
            array('id' => '24','code' => 'BM','name' =>  'Bermuda','numcode' => '60','phonecode' => '1441'),
            array('id' => '25','code' => 'BT','name' =>  'Bhutan','numcode' => '64','phonecode' => '975'),
            array('id' => '26','code' => 'BO','name' =>  'Bolivia','numcode' => '68','phonecode' => '591'),
            array('id' => '27','code' => 'BA','name' =>  'Bosnia and Herzegovina','numcode' => '70','phonecode' => '387'),
            array('id' => '28','code' => 'BW','name' => 'Botswana','numcode' => '72','phonecode' => '267'),
            array('id' => '29','code' => 'BV','name' =>  'Bouvet Island','numcode' => NULL,'phonecode' => '0'),
            array('id' => '30','code' => 'BR','name' =>  'Brazil','numcode' => '76','phonecode' => '55'),
            array('id' => '31','code' => 'IO','name' =>  'British Indian Ocean Territory','numcode' => NULL,'phonecode' => '246'),
            array('id' => '32','code' => 'BN','name' => 'Brunei Darussalam','numcode' => '96','phonecode' => '673'),
            array('id' => '33','code' => 'BG','name' => 'Bulgaria','numcode' => '100','phonecode' => '359'),
            array('id' => '34','code' => 'BF','name' => 'Burkina Faso','numcode' => '854','phonecode' => '226'),
            array('id' => '35','code' => 'BI','name' => 'Burundi','numcode' => '108','phonecode' => '257'),
            array('id' => '36','code' => 'KH','name' => 'Cambodia','numcode' => '116','phonecode' => '855'),
            array('id' => '37','code' => 'CM','name' => 'Cameroon','numcode' => '120','phonecode' => '237'),
            array('id' => '38','code' => 'CA','name' => 'Canada','numcode' => '124','phonecode' => '1'),
            array('id' => '39','code' => 'CV','name' => 'Cape Verde','numcode' => '132','phonecode' => '238'),
            array('id' => '40','code' => 'KY','name' => 'Cayman Islands','numcode' => '136','phonecode' => '1345'),
            array('id' => '41','code' => 'CF','name' => 'Central African Republic','numcode' => '140','phonecode' => '236'),
            array('id' => '42','code' => 'TD','name' =>'Chad','numcode' => '148','phonecode' => '235'),
            array('id' => '43','code' => 'CL','name' => 'Chile','numcode' => '152','phonecode' => '56'),
            array('id' => '44','code' => 'CN','name' => 'China','numcode' => '156','phonecode' => '86'),
            array('id' => '45','code' => 'CX','name' => 'Christmas Island','numcode' => NULL,'phonecode' => '61'),
            array('id' => '46','code' => 'CC','name' => 'Cocos (Keeling) Islands','numcode' => NULL,'phonecode' => '672'),
            array('id' => '47','code' => 'CO','name' => 'Colombia','numcode' => '170','phonecode' => '57'),
            array('id' => '48','code' => 'KM','name' => 'Comoros','numcode' => '174','phonecode' => '269'),
            array('id' => '49','code' => 'CG','name' => 'Congo','numcode' => '178','phonecode' => '242'),
            array('id' => '50','code' => 'CD','name' => 'Congo, the Democratic Republic of the','numcode' => '180','phonecode' => '242'),
            array('id' => '51','code' => 'CK','name' => 'Cook Islands','numcode' => '184','phonecode' => '682'),
            array('id' => '52','code' => 'CR','name' => 'Costa Rica','numcode' => '188','phonecode' => '506'),
            array('id' => '53','code' => 'CI','name' => 'Cote D\'Ivoire','numcode' => '384','phonecode' => '225'),
            array('id' => '54','code' => 'HR','name' => 'Croatia','numcode' => '191','phonecode' => '385'),
            array('id' => '55','code' => 'CU','name' => 'Cuba','numcode' => '192','phonecode' => '53'),
            array('id' => '56','code' => 'CY','name' => 'Cyprus','numcode' => '196','phonecode' => '357'),
            array('id' => '57','code' => 'CZ','name' => 'Czech Republic','numcode' => '203','phonecode' => '420'),
            array('id' => '58','code' => 'DK','name' => 'Denmark','numcode' => '208','phonecode' => '45'),
            array('id' => '59','code' => 'DJ','name' => 'Djibouti','numcode' => '262','phonecode' => '253'),
            array('id' => '60','code' => 'DM','name' => 'Dominica','numcode' => '212','phonecode' => '1767'),
            array('id' => '61','code' => 'DO','name' => 'Dominican Republic','numcode' => '214','phonecode' => '1809'),
            array('id' => '62','code' => 'EC','name' => 'Ecuador','numcode' => '218','phonecode' => '593'),
            array('id' => '63','code' => 'EG','name' => 'Egypt','numcode' => '818','phonecode' => '20'),
            array('id' => '64','code' => 'SV','name' => 'El Salvador','numcode' => '222','phonecode' => '503'),
            array('id' => '65','code' => 'GQ','name' => 'Equatorial Guinea','numcode' => '226','phonecode' => '240'),
            array('id' => '66','code' => 'ER','name' => 'Eritrea','numcode' => '232','phonecode' => '291'),
            array('id' => '67','code' => 'EE','name' => 'Estonia','numcode' => '233','phonecode' => '372'),
            array('id' => '68','code' => 'ET','name' => 'Ethiopia','numcode' => '231','phonecode' => '251'),
            array('id' => '69','code' => 'FK','name' => 'Falkland Islands (Malvinas)','numcode' => '238','phonecode' => '500'),
            array('id' => '70','code' => 'FO','name' => 'Faroe Islands','numcode' => '234','phonecode' => '298'),
            array('id' => '71','code' => 'FJ','name' => 'Fiji','numcode' => '242','phonecode' => '679'),
            array('id' => '72','code' => 'FI','name' => 'Finland','numcode' => '246','phonecode' => '358'),
            array('id' => '73','code' => 'FR','name' => 'France','numcode' => '250','phonecode' => '33'),
            array('id' => '74','code' => 'GF','name' => 'French Guiana','numcode' => '254','phonecode' => '594'),
            array('id' => '75','code' => 'PF','name' => 'French Polynesia','numcode' => '258','phonecode' => '689'),
            array('id' => '76','code' => 'TF','name' => 'French Southern Territories','numcode' => NULL,'phonecode' => '0'),
            array('id' => '77','code' => 'GA','name' => 'Gabon','numcode' => '266','phonecode' => '241'),
            array('id' => '78','code' => 'GM','name' => 'Gambia','numcode' => '270','phonecode' => '220'),
            array('id' => '79','code' => 'GE','name' => 'Georgia','numcode' => '268','phonecode' => '995'),
            array('id' => '80','code' => 'DE','name' => 'Germany','numcode' => '276','phonecode' => '49'),
            array('id' => '81','code' => 'GH','name' =>  'Ghana','numcode' => '288','phonecode' => '233'),
            array('id' => '82','code' => 'GI','name' => 'Gibraltar','numcode' => '292','phonecode' => '350'),
            array('id' => '83','code' => 'GR','name' => 'Greece','numcode' => '300','phonecode' => '30'),
            array('id' => '84','code' => 'GL','name' => 'Greenland','numcode' => '304','phonecode' => '299'),
            array('id' => '85','code' => 'GD','name' => 'Grenada','numcode' => '308','phonecode' => '1473'),
            array('id' => '86','code' => 'GP','name' => 'Guadeloupe','numcode' => '312','phonecode' => '590'),
            array('id' => '87','code' => 'GU','name' => 'Guam','numcode' => '316','phonecode' => '1671'),
            array('id' => '88','code' => 'GT','name' => 'Guatemala','numcode' => '320','phonecode' => '502'),
            array('id' => '89','code' => 'GN','name' => 'Guinea','numcode' => '324','phonecode' => '224'),
            array('id' => '90','code' => 'GW','name' => 'Guinea-Bissau','numcode' => '624','phonecode' => '245'),
            array('id' => '91','code' => 'GY','name' => 'Guyana','numcode' => '328','phonecode' => '592'),
            array('id' => '92','code' => 'HT','name' => 'Haiti','numcode' => '332','phonecode' => '509'),
            array('id' => '93','code' => 'HM','name' => 'Heard Island and Mcdonald Islands','numcode' => NULL,'phonecode' => '0'),
            array('id' => '94','code' => 'VA','name' => 'Holy See (Vatican City State)','numcode' => '336','phonecode' => '39'),
            array('id' => '95','code' => 'HN','name' => 'HND','numcode' => '340','phonecode' => '504'),
            array('id' => '96','code' => 'HK','name' => 'HKG','numcode' => '344','phonecode' => '852'),
            array('id' => '97','code' => 'HU','name' => 'Hungary','numcode' => '348','phonecode' => '36'),
            array('id' => '98','code' => 'IS','name' => 'Iceland','numcode' => '352','phonecode' => '354'),
            array('id' => '99','code' => 'IN','name' => 'India','numcode' => '356','phonecode' => '91'),
            array('id' => '100','code' => 'ID','name' => 'Indonesia','numcode' => '360','phonecode' => '62'),
            array('id' => '101','code' => 'IR','name' => 'Iran, Islamic Republic of','numcode' => '364','phonecode' => '98'),
            array('id' => '102','code' => 'IQ','name' => 'Iraq','numcode' => '368','phonecode' => '964'),
            array('id' => '103','code' => 'IE','name' => 'Ireland','numcode' => '372','phonecode' => '353'),
             array('id' => '105','code' => 'IT','name' => 'Italy','numcode' => '380','phonecode' => '39'),
            array('id' => '106','code' => 'JM','name' => 'Jamaica','numcode' => '388','phonecode' => '1876'),
            array('id' => '107','code' => 'JP','name' => 'Japan','numcode' => '392','phonecode' => '81'),
            array('id' => '108','code' => 'JO','name' => 'Jordan','numcode' => '400','phonecode' => '962'),
            array('id' => '109','code' => 'KZ','name' => 'Kazakhstan','numcode' => '398','phonecode' => '7'),
            array('id' => '110','code' => 'KE','name' => 'Kenya','numcode' => '404','phonecode' => '254'),
            array('id' => '111','code' => 'KI','name' => 'Kiribati','numcode' => '296','phonecode' => '686'),
            array('id' => '112','code' => 'KP','name' => 'Korea, Democratic People\'s Republic of','numcode' => '408','phonecode' => '850'),
            array('id' => '113','code' => 'KR','name' => 'Korea, Republic of','numcode' => '410','phonecode' => '82'),
            array('id' => '114','code' => 'KW','name' => 'Kuwait','numcode' => '414','phonecode' => '965'),
            array('id' => '115','code' => 'KG','name' => 'Kyrgyzstan','numcode' => '417','phonecode' => '996'),
            array('id' => '116','code' => 'LA','name' => 'Lao People\'s Democratic Republic','numcode' => '418','phonecode' => '856'),
            array('id' => '117','code' => 'LV','name' => 'Latvia','numcode' => '428','phonecode' => '371'),
            array('id' => '118','code' => 'LB','name' => 'Lebanon','numcode' => '422','phonecode' => '961'),
            array('id' => '119','code' => 'LS','name' => 'Lesotho','numcode' => '426','phonecode' => '266'),
            array('id' => '120','code' => 'LR','name' => 'Liberia','numcode' => '430','phonecode' => '231'),
            array('id' => '121','code' => 'LY','name' => 'Libyan Arab Jamahiriya','numcode' => '434','phonecode' => '218'),
            array('id' => '122','code' => 'LI','name' => 'Liechtenstein','numcode' => '438','phonecode' => '423'),
            array('id' => '123','code' => 'LT','name' => 'Lithuania','numcode' => '440','phonecode' => '370'),
            array('id' => '124','code' => 'LU','name' => 'Luxembourg','numcode' => '442','phonecode' => '352'),
            array('id' => '125','code' => 'MO','name' => 'Macao','numcode' => '446','phonecode' => '853'),
            array('id' => '126','code' => 'MK','name' => 'Macedonia, the Former Yugoslav Republic of','numcode' => '807','phonecode' => '389'),
            array('id' => '127','code' => 'MG','name' => 'Madagascar','numcode' => '450','phonecode' => '261'),
            array('id' => '128','code' => 'MW','name' => 'Malawi','numcode' => '454','phonecode' => '265'),
            array('id' => '129','code' => 'MY','name' => 'Malaysia','numcode' => '458','phonecode' => '60'),
            array('id' => '130','code' => 'MV','name' => 'Maldives','numcode' => '462','phonecode' => '960'),
            array('id' => '131','code' => 'ML','name' => 'Mali','numcode' => '466','phonecode' => '223'),
            array('id' => '132','code' => 'MT','name' => 'Malta','numcode' => '470','phonecode' => '356'),
            array('id' => '133','code' => 'MH','name' => 'Marshall Islands','numcode' => '584','phonecode' => '692'),
            array('id' => '134','code' => 'MQ','name' => 'Martinique','numcode' => '474','phonecode' => '596'),
            array('id' => '135','code' => 'MR','name' => 'Mauritania','numcode' => '478','phonecode' => '222'),
            array('id' => '136','code' => 'MU','name' => 'Mauritius','numcode' => '480','phonecode' => '230'),
            array('id' => '137','code' => 'YT','name' => 'Mayotte','numcode' => NULL,'phonecode' => '269'),
            array('id' => '138','code' => 'MX','name' => 'Mexico','numcode' => '484','phonecode' => '52'),
            array('id' => '139','code' => 'FM','name' => 'Micronesia, Federated States of','numcode' => '583','phonecode' => '691'),
            array('id' => '140','code' => 'MD','name' => 'Moldova, Republic of','numcode' => '498','phonecode' => '373'),
            array('id' => '141','code' => 'MC','name' => 'Monaco','numcode' => '492','phonecode' => '377'),
            array('id' => '142','code' => 'MN','name' => 'Mongolia','numcode' => '496','phonecode' => '976'),
            array('id' => '143','code' => 'MS','name' => 'Montserrat','numcode' => '500','phonecode' => '1664'),
            array('id' => '144','code' => 'MA','name' => 'Morocco','numcode' => '504','phonecode' => '212'),
            array('id' => '145','code' => 'MZ','name' => 'Mozambique','numcode' => '508','phonecode' => '258'),
            array('id' => '146','code' => 'MM','name' => 'Myanmar','numcode' => '104','phonecode' => '95'),
            array('id' => '147','code' => 'NA','name' => 'Namibia','numcode' => '516','phonecode' => '264'),
            array('id' => '148','code' => 'NR','name' => 'Nauru','numcode' => '520','phonecode' => '674'),
            array('id' => '149','code' => 'NP','name' =>'Nepal','numcode' => '524','phonecode' => '977'),
            array('id' => '150','code' => 'NL','name' => 'Netherlands','numcode' => '528','phonecode' => '31'),
            array('id' => '151','code' => 'AN','name' => 'Netherlands Antilles','numcode' => '530','phonecode' => '599'),
            array('id' => '152','code' => 'NC','name' => 'New Caledonia','numcode' => '540','phonecode' => '687'),
            array('id' => '153','code' => 'NZ','name' => 'New Zealand','numcode' => '554','phonecode' => '64'),
            array('id' => '154','code' => 'NI','name' => 'Nicaragua','numcode' => '558','phonecode' => '505'),
            array('id' => '155','code' => 'NE','name' => 'Niger','numcode' => '562','phonecode' => '227'),
            array('id' => '156','code' => 'NG','name' => 'Nigeria','numcode' => '566','phonecode' => '234'),
            array('id' => '157','code' => 'NU','name' => 'Niue','numcode' => '570','phonecode' => '683'),
            array('id' => '158','code' => 'NF','name' => 'Norfolk Island','numcode' => '574','phonecode' => '672'),
            array('id' => '159','code' => 'MP','name' => 'Northern Mariana Islands','numcode' => '580','phonecode' => '1670'),
            array('id' => '160','code' => 'NO','name' => 'Norway','numcode' => '578','phonecode' => '47'),
            array('id' => '161','code' => 'OM','name' => 'Oman','numcode' => '512','phonecode' => '968'),
            array('id' => '162','code' => 'PK','name' => 'Pakistan','numcode' => '586','phonecode' => '92'),
            array('id' => '163','code' => 'PW','name' => 'Palau','numcode' => '585','phonecode' => '680'),
            array('id' => '164','code' => 'PS','name' => 'Palestinian Territory, Occupied','numcode' => NULL,'phonecode' => '970'),
            array('id' => '165','code' => 'PA','name' => 'Panama','numcode' => '591','phonecode' => '507'),
            array('id' => '166','code' => 'PG','name' => 'Papua New Guinea','numcode' => '598','phonecode' => '675'),
            array('id' => '167','code' => 'PY','name' => 'Paraguay','numcode' => '600','phonecode' => '595'),
            array('id' => '168','code' => 'PE','name' => 'Peru','numcode' => '604','phonecode' => '51'),
            array('id' => '169','code' => 'PH','name' => 'Philippines','numcode' => '608','phonecode' => '63'),
            array('id' => '170','code' => 'PN','name' => 'Pitcairn','numcode' => '612','phonecode' => '0'),
            array('id' => '171','code' => 'PL','name' => 'Poland','numcode' => '616','phonecode' => '48'),
            array('id' => '172','code' => 'PT','name' => 'Portugal','numcode' => '620','phonecode' => '351'),
            array('id' => '173','code' => 'PR','name' => 'Puerto Rico','numcode' => '630','phonecode' => '1787'),
            array('id' => '174','code' => 'QA','name' => 'Qatar','numcode' => '634','phonecode' => '974'),
            array('id' => '175','code' => 'RE','name' => 'Reunion','numcode' => '638','phonecode' => '262'),
            array('id' => '176','code' => 'RO','name' => 'Romania','numcode' => '642','phonecode' => '40'),
            array('id' => '177','code' => 'RU','name' => 'Russian Federation','numcode' => '643','phonecode' => '70'),
            array('id' => '178','code' => 'RW','name' => 'Rwanda','numcode' => '646','phonecode' => '250'),
            array('id' => '179','code' => 'SH','name' => 'Saint Helena','numcode' => '654','phonecode' => '290'),
            array('id' => '180','code' => 'KN','name' => 'Saint Kitts and Nevis','numcode' => '659','phonecode' => '1869'),
            array('id' => '181','code' => 'LC','name' => 'Saint Lucia','numcode' => '662','phonecode' => '1758'),
            array('id' => '182','code' => 'PM','name' => 'Saint Pierre and Miquelon','numcode' => '666','phonecode' => '508'),
            array('id' => '183','code' => 'VC','name' => 'Saint Vincent and the Grenadines','numcode' => '670','phonecode' => '1784'),
            array('id' => '184','code' => 'WS','name' => 'Samoa','numcode' => '882','phonecode' => '684'),
            array('id' => '185','code' => 'SM','name' => 'San Marino','numcode' => '674','phonecode' => '378'),
            array('id' => '186','code' => 'ST','name' => 'Sao Tome and Principe','numcode' => '678','phonecode' => '239'),
            array('id' => '187','code' => 'SA','name' => 'Saudi Arabia','numcode' => '682','phonecode' => '966'),
            array('id' => '188','code' => 'SN','name' => 'Senegal','numcode' => '686','phonecode' => '221'),
            array('id' => '189','code' => 'CS','name' => 'Serbia and Montenegro','numcode' => NULL,'phonecode' => '381'),
            array('id' => '190','code' => 'SC','name' => 'Seychelles','numcode' => '690','phonecode' => '248'),
            array('id' => '191','code' => 'SL','name' => 'Sierra Leone','numcode' => '694','phonecode' => '232'),
            array('id' => '192','code' => 'SG','name' => 'Singapore','numcode' => '702','phonecode' => '65'),
            array('id' => '193','code' => 'SK','name' => 'Slovakia','numcode' => '703','phonecode' => '421'),
            array('id' => '194','code' => 'SI','name' => 'Slovenia','numcode' => '705','phonecode' => '386'),
            array('id' => '195','code' => 'SB','name' => 'Solomon Islands','numcode' => '90','phonecode' => '677'),
            array('id' => '196','code' => 'SO','name' => 'Somalia','numcode' => '706','phonecode' => '252'),
            array('id' => '197','code' => 'ZA','name' => 'South Africa','numcode' => '710','phonecode' => '27'),
            array('id' => '198','code' => 'GS','name' => 'South Georgia and the South Sandwich Islands','numcode' => NULL,'phonecode' => '0'),
            array('id' => '199','code' => 'ES','name' => 'Spain','numcode' => '724','phonecode' => '34'),
            array('id' => '200','code' => 'LK','name' => 'Sri Lanka','numcode' => '144','phonecode' => '94'),
            array('id' => '201','code' => 'SD','name' => 'Sudan','numcode' => '736','phonecode' => '249'),
            array('id' => '202','code' => 'SR','name' => 'Suriname','numcode' => '740','phonecode' => '597'),
            array('id' => '203','code' => 'SJ','name' => 'Svalbard and Jan Mayen','numcode' => '744','phonecode' => '47'),
            array('id' => '204','code' => 'SZ','name' => 'Swaziland','numcode' => '748','phonecode' => '268'),
            array('id' => '205','code' => 'SE','name' => 'Sweden','numcode' => '752','phonecode' => '46'),
            array('id' => '206','code' => 'CH','name' => 'Switzerland','numcode' => '756','phonecode' => '41'),
            array('id' => '207','code' => 'SY','name' => 'Syrian Arab Republic','numcode' => '760','phonecode' => '963'),
            array('id' => '208','code' => 'TW','name' => 'Taiwan, Province of China','numcode' => '158','phonecode' => '886'),
            array('id' => '209','code' => 'TJ','name' => 'Tajikistan','numcode' => '762','phonecode' => '992'),
            array('id' => '210','code' => 'TZ','name' => 'Tanzania, United Republic of','numcode' => '834','phonecode' => '255'),
            array('id' => '211','code' => 'TH','name' => 'Thailand','numcode' => '764','phonecode' => '66'),
            array('id' => '212','code' => 'TL','name' => 'Timor-Leste','numcode' => NULL,'phonecode' => '670'),
            array('id' => '213','code' => 'TG','name' => 'Togo','numcode' => '768','phonecode' => '228'),
            array('id' => '214','code' => 'TK','name' => 'Tokelau','numcode' => '772','phonecode' => '690'),
            array('id' => '215','code' => 'TO','name' => 'Tonga','numcode' => '776','phonecode' => '676'),
            array('id' => '216','code' => 'TT','name' => 'Trinidad and Tobago','numcode' => '780','phonecode' => '1868'),
            array('id' => '217','code' => 'TN','name' => 'Tunisia','numcode' => '788','phonecode' => '216'),
            array('id' => '218','code' => 'TR','name' => 'Turkey','numcode' => '792','phonecode' => '90'),
            array('id' => '219','code' => 'TM','name' => 'Turkmenistan','numcode' => '795','phonecode' => '7370'),
            array('id' => '220','code' => 'TC','name' => 'Turks and Caicos Islands','numcode' => '796','phonecode' => '1649'),
            array('id' => '221','code' => 'TV','name' => 'Tuvalu','numcode' => '798','phonecode' => '688'),
            array('id' => '222','code' => 'UG','name' => 'Uganda','numcode' => '800','phonecode' => '256'),
            array('id' => '223','code' => 'UA','name' => 'Ukraine','numcode' => '804','phonecode' => '380'),
            array('id' => '224','code' => 'AE','name' => 'United Arab Emirates','numcode' => '784','phonecode' => '971'),
            array('id' => '225','code' => 'GB','name' => 'United Kingdom','numcode' => '826','phonecode' => '44'),
            array('id' => '226','code' => 'US','name' => 'United States','numcode' => '840','phonecode' => '1'),
            array('id' => '227','code' => 'UM','name' => 'United States Minor Outlying Islands','numcode' => NULL,'phonecode' => '1'),
            array('id' => '228','code' => 'UY','name' => 'Uruguay','numcode' => '858','phonecode' => '598'),
            array('id' => '229','code' => 'UZ','name' => 'Uzbekistan','numcode' => '860','phonecode' => '998'),
            array('id' => '230','code' => 'VU','name' => 'Vanuatu','numcode' => '548','phonecode' => '678'),
            array('id' => '231','code' => 'VE','name' => 'Venezuela','numcode' => '862','phonecode' => '58'),
            array('id' => '232','code' => 'VN','name' => 'Viet Nam','numcode' => '704','phonecode' => '84'),
            array('id' => '233','code' => 'VG','name' => 'Virgin Islands, British','numcode' => '92','phonecode' => '1284'),
            array('id' => '234','code' => 'VI','name' => 'Virgin Islands, U.s.','numcode' => '850','phonecode' => '1340'),
            array('id' => '235','code' => 'WF','name' => 'Wallis and Futuna','numcode' => '876','phonecode' => '681'),
            array('id' => '236','code' => 'EH','name' => 'Western Sahara','numcode' => '732','phonecode' => '212'),
            array('id' => '237','code' => 'YE','name' => 'Yemen','numcode' => '887','phonecode' => '967'),
            array('id' => '238','code' => 'ZM','name' => 'Zambia','numcode' => '894','phonecode' => '260'),
            array('id' => '239','code' => 'ZW','name' => 'Zimbabwe','numcode' => '716','phonecode' => '263'),
            array('id' => '240','code' => 'RS','name' => 'Serbia','numcode' => '688','phonecode' => '381'),
            array('id' => '241','code' => 'AP','name' => 'Asia / Pacific Region','numcode' => '0','phonecode' => '0'),
            array('id' => '242','code' => 'ME','name' => 'Montenegro','numcode' => '499','phonecode' => '382'),
            array('id' => '243','code' => 'AX','name' => 'Aland Islands','numcode' => '248','phonecode' => '358'),
            array('id' => '244','code' => 'BQ','name' => 'Bonaire, Sint Eustatius and Saba','numcode' => '535','phonecode' => '599'),
            array('id' => '245','code' => 'CW','name' => 'Curacao','numcode' => '531','phonecode' => '599'),
            array('id' => '246','code' => 'GG','name' => 'Guernsey','numcode' => '831','phonecode' => '44'),
            array('id' => '247','code' => 'IM','name' => 'Isle of Man','numcode' => '833','phonecode' => '44'),
            array('id' => '248','code' => 'JE','name' => 'Jersey','numcode' => '832','phonecode' => '44'),
            array('id' => '249','code' => 'XK','name' => 'Kosovo','numcode' => '0','phonecode' => '381'),
            array('id' => '250','code' => 'BL','name' => 'Saint Barthelemy','numcode' => '652','phonecode' => '590'),
            array('id' => '251','code' => 'MF','name' => 'Saint Martin','numcode' => '663','phonecode' => '590'),
            array('id' => '252','code' => 'SX','name' => 'Sint Maarten','numcode' => '534','phonecode' => '1'),
            array('id' => '253','code' => 'SS','name' => 'South Sudan','numcode' => '728','phonecode' => '211')
        );

        DB::table('countries')->insert($countries);
    }
}
